# Generated by Django 5.0.1 on 2024-01-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_enderecos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='logradouro',
        ),
        migrations.AddField(
            model_name='endereco',
            name='city',
            field=models.CharField(default='Capital', max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='neighborhood',
            field=models.CharField(default='Bairro desconhecido', max_length=50, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='service',
            field=models.CharField(default='Servico desconhecido', max_length=50, verbose_name='Serviço'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='state',
            field=models.CharField(default='NA', max_length=2, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='street',
            field=models.CharField(default='Rua Desconhecida', max_length=255, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(default='00000000', max_length=8, verbose_name='CEP'),
        ),
    ]
