# Generated by Django 5.0.1 on 2024-01-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_enderecos', '0002_remove_endereco_cidade_remove_endereco_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='endereco_ativo',
            field=models.BooleanField(default=True),
        ),
    ]
